### ISSUE TITLE
random oob warps.

### ISSUE THREAD

**Issue by guydude64** [Zephiles/TTYD-Randomizers#2]
I've noticed that when using the randomizer on dolphin, every so often, going to a different area by way of loading zone will occasionally set me down in an out of bounds area, infinitely falling beneath the area over and over again, lifting me back up near the actual ground, but unable to ever reach it, and so am forced to reset whenever I reach such an occurance.

**Comment by Zephiles** [comment]
You need to use the code to change which Loading Zone you came out of. It's L + D-Pad direction. You then need to reload the room with L+B for it to take effect.
